sudo: required
services: 
  - docker

before_install:
  - docker build -t Harryle123/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run Harryle123/react-test npm test -- --coverage

after_success:
  - docker build -t Harryle123/multi-client  ./client
  - docker build -t Harryle123/multi-ngnix  ./ngnix
  - docker build -t Harryle123/multi-server  ./server
  - docker build -t Harryle123/multi-worker  ./worker
#login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push Harryle123/multi-client
  - docker push Harryle123/multi-ngnix
  - docker push Harryle123/multi-server
  - docker push Harryle123/multi-worker
