language: node_js
sudo: required
services: 
  - docker

before_install:
  - docker build -t harrylee123/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true harrylee123/react-test npm test

after_success:
  - docker build -t harrylee123/multi-client  ./client
  - docker build -t harrylee123/multi-nginx  ./nginx
  - docker build -t harrylee123/multi-server  ./server
  - docker build -t harrylee123/multi-worker  ./worker
#login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push harrylee123/multi-client
  - docker push harrylee123/multi-nginx
  - docker push harrylee123/multi-server
  - docker push harrylee123/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker-1
  env: Multidocker1-env
  bucket_name: elasticbeanstalk-us-east-2-290703000442
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY